name: Basic Workflow Dispatch Example

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Congrats! you have learned the basic manual trigger workflow"
      
