# This is a basic workflow to help you get started with Actions

name: Getting Started

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 1. what is in the direcdtopry?
          ls -a
          echo
          echo 2. Is Java installed?
          java -version
          echo
          echo 3. is git installed?
          git --version
          echo
          echo 4. what about build tools?
          mvn --version
          gradle --version
          ant -version
          echo
          echo 5. is docker installed?
          docker --version
          echo
          echo 6. where is the Andrroid SDK Root?
          echo $ANDROID_SDK_ROOT
          echo
          echo 7. what is the workspace location
          echo $RUNNER_WORKSPACE
          echo
          echo 8. who is running the script?
          whoami
          echo
          echo 9. how is the disk laid out?
          df
          echo 10. what environment variables are available?
          env
          
          
          
          
          
