name: upload-artifacts #

on:
  push:
    branches:
    - release

jobs:
  archive build artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - create a temporary artifact download folder
        run: mkdir downloads
      - name: Step 2 - Add artiofacts to publish to the temp folder
        run: |
          cd downloads
          echo 'alphs'  > alpha.html
          echo 'bravo'  > bravp.html
          echo 'charlie'  > charlie.html
          cd ..
      - name: Step 3 - Use the Artifact Github Action
        uses: actions/upload-artifacts@v2
        with:
          name: assets-for-download
          path: downloads
       
